USE [master]
GO
/****** Object:  Database [HDL]    Script Date: 20/6/2020 12:13:10 a. m. ******/
CREATE DATABASE [HDL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HDL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HDL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HDL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HDL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HDL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HDL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HDL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HDL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HDL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HDL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HDL] SET ARITHABORT OFF 
GO
ALTER DATABASE [HDL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HDL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HDL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HDL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HDL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HDL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HDL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HDL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HDL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HDL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HDL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HDL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HDL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HDL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HDL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HDL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HDL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HDL] SET RECOVERY FULL 
GO
ALTER DATABASE [HDL] SET  MULTI_USER 
GO
ALTER DATABASE [HDL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HDL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HDL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HDL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HDL] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'HDL', N'ON'
GO
ALTER DATABASE [HDL] SET QUERY_STORE = OFF
GO
USE [HDL]
GO
/****** Object:  Table [dbo].[Asignaturas]    Script Date: 20/6/2020 12:13:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Asignaturas](
	[IdAsignatura] [varchar](6) NOT NULL,
	[Nombre_Asignatura] [varchar](50) NOT NULL,
	[Creditos] [int] NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Asignaturas] PRIMARY KEY CLUSTERED 
(
	[IdAsignatura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Eventos]    Script Date: 20/6/2020 12:13:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Eventos](
	[IdLaboratorio] [int] NOT NULL,
	[IdAsignatura] [varchar](6) NOT NULL,
	[HoraInicio] [time](7) NOT NULL,
	[HoraFinal] [time](7) NOT NULL,
	[Profesor] [int] NOT NULL,
	[DiaSemana] [int] IDENTITY(1,1) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Eventos] PRIMARY KEY CLUSTERED 
(
	[IdLaboratorio] ASC,
	[IdAsignatura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Laboratorios]    Script Date: 20/6/2020 12:13:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Laboratorios](
	[IdLaboratorio] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Lab] [varchar](1) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Laboratorios] PRIMARY KEY CLUSTERED 
(
	[IdLaboratorio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesores]    Script Date: 20/6/2020 12:13:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesores](
	[IdProfesor] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Profesor] [varchar](50) NOT NULL,
	[Edad] [int] NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Profesores] PRIMARY KEY CLUSTERED 
(
	[IdProfesor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Weekdays]    Script Date: 20/6/2020 12:13:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Weekdays](
	[IdWeekday] [int] IDENTITY(1,1) NOT NULL,
	[Dia_Semana] [varchar](9) NOT NULL,
 CONSTRAINT [PK_Weekday] PRIMARY KEY CLUSTERED 
(
	[IdWeekday] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Eventos]  WITH CHECK ADD  CONSTRAINT [FK_Eventos_Asignaturas] FOREIGN KEY([IdAsignatura])
REFERENCES [dbo].[Asignaturas] ([IdAsignatura])
GO
ALTER TABLE [dbo].[Eventos] CHECK CONSTRAINT [FK_Eventos_Asignaturas]
GO
ALTER TABLE [dbo].[Eventos]  WITH CHECK ADD  CONSTRAINT [FK_Eventos_Laboratorios] FOREIGN KEY([IdLaboratorio])
REFERENCES [dbo].[Laboratorios] ([IdLaboratorio])
GO
ALTER TABLE [dbo].[Eventos] CHECK CONSTRAINT [FK_Eventos_Laboratorios]
GO
ALTER TABLE [dbo].[Eventos]  WITH CHECK ADD  CONSTRAINT [FK_Eventos_Profesores] FOREIGN KEY([Profesor])
REFERENCES [dbo].[Profesores] ([IdProfesor])
GO
ALTER TABLE [dbo].[Eventos] CHECK CONSTRAINT [FK_Eventos_Profesores]
GO
ALTER TABLE [dbo].[Eventos]  WITH CHECK ADD  CONSTRAINT [FK_Eventos_Weekdays] FOREIGN KEY([DiaSemana])
REFERENCES [dbo].[Weekdays] ([IdWeekday])
GO
ALTER TABLE [dbo].[Eventos] CHECK CONSTRAINT [FK_Eventos_Weekdays]
GO
USE [master]
GO
ALTER DATABASE [HDL] SET  READ_WRITE 
GO
